dcommon_args:
  training_type: "cross_silo"
  random_seed: 0
  scenario: "horizontal"
  using_mlops: false
  config_version: release
  # name: "Train_BDD20kGT_50E" # yolo
  name: "MultiDomain_BDD" # yolo
  project: "runs/train/multidomain" # yolo
  exist_ok: true # yolo

environment_args:
  bootstrap: ./config/bootstrap.sh

train_args:
  federated_optimizer: "FedAvg"
  client_id_list:
  client_num_in_total: 3
  client_num_per_round: 3
  comm_round: 50
  epochs: 10
  batch_size: 32
  client_optimizer: sgd
  lr: 0.01
  weight_decay: 0.0005
  checkpoint_interval: 10
  server_checkpoint_interval: 1
  cache_train_data: False
  cache_test_data: False

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 3
  using_gpu: true
  gpu_mapping_file: ./config/gpu_mapping_new.yaml
  gpu_mapping_key: mapping_config3_1_shoaib #mapping_config2_1_shoaib #mapping_config5_1_shoaib
  gpu_ids: [0,1,2,3,4,5,6,7]

comm_args:
  #backend: "MPI"
  #is_mobile: 0
  backend: "GRPC"
  grpc_ipconfig_path: config/grpc_ipconfig.csv
  #backend: "MQTT_S3"
  #mqtt_config_path: ./config/mqtt_config.yaml
  #s3_config_path: ./config/s3_config.yaml

tracking_args:
  log_file_dir: ./log
  enable_wandb: true
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_object_detection


data_args:
  dataset: "3class_bdd"
  data_cache_dir: ./fedcv_data
  partition_method: "homo"
  partition_alpha: 0.5
  data_conf: "config/multi_domain/data/3class_bdd.yaml" # yolo
  img_size: [640, 640] # [640, 640]

# data_args:
#   dataset: "3class_waymo"
#   data_cache_dir: ./fedcv_data
#   partition_method: "homo"
#   partition_alpha: 0.5
#   data_conf: "config/multi_domain/data/3class_waymo.yaml" # yolo
#   img_size: [640, 640] # [640, 640]

# data_args:
#   dataset: "3class_agroverse"
#   data_cache_dir: ./fedcv_data
#   partition_method: "homo"
#   partition_alpha: 0.5
#   data_conf: "config/multi_domain/data/3class_agroverse.yaml" # yolo
#   img_size: [640, 640] # [640, 640]


model_args:
  model: "yolov5" # "yolov5"
  class_num: 3
  # yolo_cfg: "./model/yolov5/models/yolov5n.yaml" # "./model/yolov6/configs/yolov6s.py" # yolo
  # yolo_cfg: "./model/yolov5/models/yolov5s.yaml" # "./model/yolov6/configs/yolov6s.py" # yolo
  yolo_cfg: "./model/yolov5/models/yolov5s.yaml" 
  # yolo_cfg: "./model/yolov5/models/yolov5m.yaml" 
  yolo_hyp: "./config/hyps/hyp.scratch.yaml" # yolo
  yolo_opt: "./runs/train/opt.yaml"
  weights: "none"
  # weights: "/home/shoaib/FedML_MSIS_Shoaib/python/app/fedcv/object_detection/best_by_zafar_bdd3class_300.pt"
  # weights: "/home/shoaib/FedML_MSIS_Shoaib/python/app/fedcv/object_detection/runs/train/Train_BDD20kGT_50E/weights/aggr_model_13.pt" 
  single_cls: false # yolo
  conf_thres: 0.001 # yolo
  iou_thres: 0.6 # for yolo NMS
  yolo_verbose: true # yolo


new_data_args:
  # new_data: "agroverse"
  # new_data_conf: "./data/3class_agroverse.yaml"
  # new_data: "waymo_cleaned"
  # new_data_conf: "./data/3class_waymo_cleaned.yaml"
  # new_data: "waymo"
  # new_data_conf: "./data/3class_waymo.yaml"
  # new_data: "bdd"
  # new_data_conf: "./data/bdd_full.yaml"
  new_data: "bdd"
  new_data_conf: "config/multi_domain/data/3class_bdd.yaml" 
  # new_data: "bdd" # "waymo"
  # new_data_conf: "./data/bdd_full.yaml" #./data/3class_waymo.yaml"

  new_data_min_rounds: -1
  min_map_for_pseudo_generation: 0.5

  use_new_data: False # False to use only original data from server
  use_new_data_pseudos: False # False to disable pseudo label generation
  use_new_data_recover: False # False to disable pseudo label recovery
  new_data_num_images_train: 5000

  use_same_training_on_all_clients: True   #FIXME: VERY VERY VERY IMPORTANT

  use_new_test_dataset: True  #Make while initial data loading. Disabled inside use_new_data function - hard coded
  new_data_num_images_test: [] # 10000 # [] for full validation data
  start_id_test: 1 # [] for random -- Only when choosing partial val data
  val_on: 0 # Perform server evaluation on  0-Old, 1-New, 2-Merged

  # use_update_from_server: True
  use_update_from_server: False
  
  use_best_from_server_clients: False
  keep_server_model_history: False
  keep_client_model_history: False

  ValClientsOnServer: False

  tmp_merge_file: "../../../../merged_list.txt"
  tmp_gt_files_train: "../../../../tmp_train.txt"
  tmp_gt_files_test: "../../../../tmp_test.txt"
  new_deepsort_config: "Yolov5_DeepSORT_PseudoLabels/deep_sort/configs/deep_sort.yaml"
  conf_thresh_low: 0.1 # Low confidence threshold for pseudo labels
  conf_thresh_high: 0.5 # High confidence threshold for pseudo labels
  iou_thres: 0.6
  psuedo_generate_clients: [0,1,2,3,4,5,6,7,8] #[0,1,2,3,4,5,6,7,8] #[1,3,5,7] # [1,2,3,4,5,6,7]
  psuedo_recovery_on_clients: [0,1,2,3,4,5,6,7,8] #[2,4,6,8]
  color_str: "bright_yellow" #bright_red, bright_green, bright_blue

  # run_name: "Train_3C_30EpR_BDD35k_Waymo5k-GT"
  # run_name: "Train_BDD20kGT_Waymo5k_GT_10EpR"
  # run_name: "Train_BDD20kGT_50E"
  run_name: "MultiDomain_BDD"
  # run_name: "Testing"
  wandb_project: "FedML-MultiDomain"
  # run_name: "FedML-MultiDomain-Yolov5s-NoServerUpdate-Scratch"
  # wandb_project: "FedML-Testing"

  # Variable Initialization
  RoundxEpoch: 0
  test_dataloader_new: []
  test_dataloader_merged: []
  # data_desc: []
  # data_desc: ["After_Training_"]
  # data_desc: ["After_Training_" ,"After_Training_New_TestD_"]
  data_desc: ["After_Training_" ,"After_Training_New_TestD_"    ,"After_Training_Merged_TestD_" ]
